# Generated by Django 5.0.3 on 2024-03-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://placehold.co/600x400?text=Food', max_length=500),
        ),
    ]
